parameters:
#    cf_user.example.class: cf\UserBundle\Example

services:
    cf.commonbundle.messenger:
        class: Cf\CommonBundle\Listener\MessengerListener
        arguments: ['@service_container']
        calls:
            - [ getError, [ @? ] ]
            - [ getSuccess, [ @? ] ]
            - [ getParseErrorsByValidator, [ @? ] ]

    cf.commonbundle.miscellaneous:
        class: Cf\CommonBundle\Listener\MiscellaneousListener
        arguments: ['@service_container']
        calls:
            - [ bindParameters, [ @?, @? ] ]

    cf.commonbundle.restapi:
        class: Cf\CommonBundle\Listener\RestApiListener